import w1 from "./assets/a4.png";

export const data = [
    {
        id: 1,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 2,
        title: "Wraith - How to get the most of season 12 and which legend is comming",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 3,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 4,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 4,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 5,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 6,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 7,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 7,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 7,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
    {
        id: 7,
        title: "Wraith - Airship Assasian",
        channelName: "Apex Legends",
        runTime: "10:00",
        views: "110K",
        timeAgo: "2 days ago",
        image: w1,
    },
]